FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 5173

# Запускаем dev-сервер
# --host 0.0.0.0 - позволяет подключаться извне контейнера
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]