import { type ITask } from '@/entities/task/model/types'

export const tasks: ITask[] = [
  // Easy - базовые операции
  {
    id: '1',
    number: 1,
    text: 'Капитализация слов в строке - базовая работа со строками',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '2',
    number: 2,
    text: 'Склеивание строк через разделитель - базовая работа с массивами',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '3',
    number: 3,
    text: 'Удаление лишнего дублирования букв - линейный проход',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '4',
    number: 4,
    text: 'Проверка строки на палиндром - простой алгоритм',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '5',
    number: 5,
    text: 'Поиск строк с подстрокой - строковый поиск',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '6',
    number: 6,
    text: 'Получение значения из объекта по пути - работа с объектами',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '7',
    number: 7,
    text: 'Конкатенация строк из объектов - обход объектов',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '8',
    number: 8,
    text: 'Реализация map - методы массивов',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '9',
    number: 9,
    text: 'Реализация filter - методы массивов',
    completed: false,
    difficulty: 'easy',
  },
  {
    id: '10',
    number: 10,
    text: 'Реализация reduce - методы массивов',
    completed: false,
    difficulty: 'easy',
  },

  // Medium - более сложные алгоритмы
  {
    id: '11',
    number: 11,
    text: 'Проверка на анаграммы - базовые структуры данных',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '12',
    number: 12,
    text: 'Проверка корректности скобок - классическая stack задача',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '13',
    number: 13,
    text: 'Проверка на панграмму - работа с множествами',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '14',
    number: 14,
    text: 'Разность массивов - работа с множествами',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '15',
    number: 15,
    text: 'Разворачивание вложенных массивов (flatten) - рекурсия/стек',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '16',
    number: 16,
    text: 'Сжатие строки - алгоритм RLE',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '17',
    number: 17,
    text: 'Найти индексы элементов для суммы - хэш-таблица',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '18',
    number: 18,
    text: 'Сжатие списка чисел в диапазоны - интервалы',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '19',
    number: 19,
    text: 'Группировка анаграмм - хэш-таблицы + сортировка',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '20',
    number: 20,
    text: 'К наиболее частых элементов - хэш-таблица + сортировка/куча',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '21',
    number: 21,
    text: 'Рекурсивная сумма всех чисел в объекте - рекурсивный обход',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '22',
    number: 22,
    text: 'Сумма всех значений в дереве - обход деревьев',
    completed: false,
    difficulty: 'medium',
  },
  {
    id: '23',
    number: 23,
    text: 'Реализация debounce - асинхронное программирование',
    completed: false,
    difficulty: 'medium',
  },

  // Hard - сложные алгоритмы
  {
    id: '24',
    number: 24,
    text: 'Найти самый глубокий максимальный элемент - обход деревьев с условиями',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '25',
    number: 25,
    text: 'Извлечение нод по типу - работа с DOM/деревьями',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '26',
    number: 26,
    text: 'Калькулятор обратной польской нотации - стек + парсинг',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '27',
    number: 27,
    text: 'Сложение чисел, представленных массивами - арифметика больших чисел',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '28',
    number: 28,
    text: 'Построение маршрута - графы/обход деревьев',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '29',
    number: 29,
    text: 'Расчет стоимости проживания в отеле - бизнес-логика + алгоритмы',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '30',
    number: 30,
    text: 'Алгоритм бинарного поиска - классический алгоритм',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '31',
    number: 31,
    text: 'Алгоритм пузырьковой сортировки - классическая сортировка',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '32',
    number: 32,
    text: 'Рекурсия - общая концепция',
    completed: false,
    difficulty: 'hard',
  },
  {
    id: '33',
    number: 33,
    text: 'Реализация промисификации - асинхронное программирование',
    completed: false,
    difficulty: 'hard',
  },
]
